import json

# Leer el notebook
notebook_path = r'd:\OneDrive\UTN\5\CienciaDeDatos_\medical-ml-predictor\PRESENTACION\presentacion_limpieza_dataset.ipynb'

with open(notebook_path, 'r', encoding='utf-8') as f:
    notebook = json.load(f)

# Encontrar la celda que contiene "📜 ANÁLISIS DEL SCRIPT DE LIMPIEZA"
target_cell_index = None
for i, cell in enumerate(notebook['cells']):
    if cell['cell_type'] == 'code':
        source = ''.join(cell['source'])
        if '📜 ANÁLISIS DEL SCRIPT DE LIMPIEZA' in source and 'Variables numéricas: MEDIANA' in source:
            target_cell_index = i
            break

if target_cell_index is None:
    print("ERROR: No se encontro la celda objetivo")
    exit(1)

print(f"Celda encontrada en indice: {target_cell_index}")

# Nueva celda de código con visualización mejorada
nueva_celda_codigo = {
    "cell_type": "code",
    "execution_count": None,
    "id": "analisis_outliers_visual",
    "metadata": {},
    "outputs": [],
    "source": [
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import pandas as pd\n",
        "\n",
        "print(\"📜 ANÁLISIS DEL SCRIPT DE LIMPIEZA\")\n",
        "print(\"=\" * 50)\n",
        "\n",
        "# Mostrar el contenido del script con explicaciones\n",
        "with open('../clean_dataset_complete.py', 'r', encoding='utf-8') as file:\n",
        "    script_content = file.read()\n",
        "\n",
        "print(\"🔧 ESTRATEGIA GENERAL DEL SCRIPT:\")\n",
        "print(\"\\n1️⃣ ELIMINACIÓN SELECTIVA DE COLUMNAS\")\n",
        "print(\"   • IDs administrativos (encounter_id, patient_id, hospital_id, icu_id)\")\n",
        "print(\"   • Columnas completamente vacías (Unnamed: 83)\")\n",
        "print(\"   • ❌ NO elimina columnas con información médica relevante\")\n",
        "\n",
        "print(\"\\n2️⃣ ESTRATEGIAS DE IMPUTACIÓN POR TIPO DE VARIABLE\")\n",
        "print(\"   📊 Variables numéricas: MEDIANA (robusta ante outliers)\")\n",
        "print(\"   📝 Variables categóricas: MODA (valor más frecuente)\")\n",
        "print(\"   🎯 Variable objetivo: ELIMINACIÓN de filas con nulls\")\n",
        "\n",
        "print(\"\\n3️⃣ ENCODING DE VARIABLES CATEGÓRICAS\")\n",
        "print(\"   🔢 LabelEncoder para convertir texto a números\")\n",
        "print(\"   ➕ Agrega columnas '_encoded' manteniendo originales\")\n",
        "\n",
        "print(\"\\n4️⃣ VERIFICACIÓN Y LIMPIEZA FINAL\")\n",
        "print(\"   ✅ Verificación de 0 valores faltantes\")\n",
        "print(\"   🗑️ Eliminación de duplicados\")\n",
        "print(\"   💾 Guardado del dataset limpio\")\n",
        "\n",
        "print(\"\\n\" + \"=\"*70)\n",
        "print(\"💡 ENFOQUE PROFUNDO: ¿Por qué MEDIANA en Variables Numéricas?\")\n",
        "print(\"=\" * 70)\n",
        "\n",
        "# ============================================================================\n",
        "# DEMOSTRACIÓN VISUAL: OUTLIERS Y SU IMPACTO\n",
        "# ============================================================================\n",
        "\n",
        "print(\"\\n🎯 EJEMPLO PRÁCTICO: Frecuencia Cardíaca de Pacientes en UCI\\n\")\n",
        "\n",
        "# Crear datos de ejemplo realistas\n",
        "# Escenario 1: Datos normales (sin outliers)\n",
        "datos_normales = np.array([72, 75, 68, 80, 78, 71, 76, 73, 79, 74])\n",
        "\n",
        "# Escenario 2: Datos con outliers (pacientes en crisis)\n",
        "datos_con_outliers = np.array([72, 75, 68, 80, 78, 71, 76, 73, 155, 180])  # 2 pacientes críticos\n",
        "\n",
        "# Calcular estadísticas\n",
        "media_normal = np.mean(datos_normales)\n",
        "mediana_normal = np.median(datos_normales)\n",
        "media_outliers = np.mean(datos_con_outliers)\n",
        "mediana_outliers = np.median(datos_con_outliers)\n",
        "\n",
        "# Crear tabla comparativa\n",
        "print(\"📊 COMPARACIÓN NUMÉRICA:\")\n",
        "print(\"-\" * 70)\n",
        "comparacion = pd.DataFrame({\n",
        "    'Escenario': ['SIN outliers', 'CON outliers (2 pacientes críticos)'],\n",
        "    'Datos': [\n",
        "        str(datos_normales.tolist()),\n",
        "        str(datos_con_outliers.tolist())\n",
        "    ],\n",
        "    'Media (Promedio)': [f\"{media_normal:.1f} lpm\", f\"{media_outliers:.1f} lpm\"],\n",
        "    'Mediana': [f\"{mediana_normal:.1f} lpm\", f\"{mediana_outliers:.1f} lpm\"],\n",
        "    'Distorsión': [\n",
        "        \"✅ Ninguna\",\n",
        "        f\"❌ Media inflada +{media_outliers - mediana_outliers:.1f} lpm\"\n",
        "    ]\n",
        "})\n",
        "\n",
        "print(comparacion.to_string(index=False))\n",
        "print(\"-\" * 70)\n",
        "\n",
        "print(\"\\n🔍 INTERPRETACIÓN:\")\n",
        "print(f\"  • La MEDIA pasó de {media_normal:.1f} a {media_outliers:.1f} lpm (+{media_outliers - media_normal:.1f})\")\n",
        "print(f\"  • La MEDIANA se mantuvo estable: {mediana_normal:.1f} → {mediana_outliers:.1f} lpm\")\n",
        "print(f\"  • Diferencia crítica: {media_outliers - mediana_outliers:.1f} lpm de distorsión\\n\")\n",
        "\n",
        "# ============================================================================\n",
        "# VISUALIZACIÓN GRÁFICA\n",
        "# ============================================================================\n",
        "\n",
        "fig, axes = plt.subplots(2, 2, figsize=(16, 10))\n",
        "fig.suptitle('🎯 IMPACTO DE OUTLIERS: Media vs Mediana en Datos Médicos', \n",
        "             fontsize=18, fontweight='bold', y=0.995)\n",
        "\n",
        "# Colores consistentes\n",
        "color_normal = '#2E86AB'\n",
        "color_outlier = '#E63946'\n",
        "color_media = '#F77F00'\n",
        "color_mediana = '#06A77D'\n",
        "\n",
        "# --- GRÁFICO 1: Distribución SIN outliers ---\n",
        "ax1 = axes[0, 0]\n",
        "ax1.scatter(range(len(datos_normales)), datos_normales, s=200, c=color_normal, \n",
        "            alpha=0.7, edgecolors='black', linewidth=2, zorder=3)\n",
        "ax1.axhline(media_normal, color=color_media, linewidth=3, linestyle='--', \n",
        "            label=f'Media = {media_normal:.1f} lpm', alpha=0.8)\n",
        "ax1.axhline(mediana_normal, color=color_mediana, linewidth=3, linestyle='-', \n",
        "            label=f'Mediana = {mediana_normal:.1f} lpm', alpha=0.8)\n",
        "ax1.set_title('📗 ESCENARIO 1: Datos Normales (sin outliers)', fontsize=14, fontweight='bold', pad=15)\n",
        "ax1.set_ylabel('Frecuencia Cardíaca (lpm)', fontsize=12, fontweight='bold')\n",
        "ax1.set_xlabel('Paciente', fontsize=12, fontweight='bold')\n",
        "ax1.legend(fontsize=11, loc='upper right', framealpha=0.95)\n",
        "ax1.grid(True, alpha=0.3, linestyle=':')\n",
        "ax1.set_ylim(60, 200)\n",
        "ax1.text(0.5, 0.95, '✅ Media y Mediana casi idénticas', \n",
        "         transform=ax1.transAxes, fontsize=11, ha='center', \n",
        "         bbox=dict(boxstyle='round', facecolor='lightgreen', alpha=0.7))\n",
        "\n",
        "# --- GRÁFICO 2: Distribución CON outliers ---\n",
        "ax2 = axes[0, 1]\n",
        "colores = [color_normal if x < 100 else color_outlier for x in datos_con_outliers]\n",
        "ax2.scatter(range(len(datos_con_outliers)), datos_con_outliers, s=200, c=colores, \n",
        "            alpha=0.7, edgecolors='black', linewidth=2, zorder=3)\n",
        "ax2.axhline(media_outliers, color=color_media, linewidth=3, linestyle='--', \n",
        "            label=f'Media = {media_outliers:.1f} lpm ⚠️', alpha=0.8)\n",
        "ax2.axhline(mediana_outliers, color=color_mediana, linewidth=3, linestyle='-', \n",
        "            label=f'Mediana = {mediana_outliers:.1f} lpm ✅', alpha=0.8)\n",
        "ax2.set_title('📕 ESCENARIO 2: Datos con Outliers (pacientes críticos)', \n",
        "              fontsize=14, fontweight='bold', pad=15)\n",
        "ax2.set_ylabel('Frecuencia Cardíaca (lpm)', fontsize=12, fontweight='bold')\n",
        "ax2.set_xlabel('Paciente', fontsize=12, fontweight='bold')\n",
        "ax2.legend(fontsize=11, loc='upper right', framealpha=0.95)\n",
        "ax2.grid(True, alpha=0.3, linestyle=':')\n",
        "ax2.set_ylim(60, 200)\n",
        "ax2.annotate('🚨 OUTLIER\\nPaciente crítico', xy=(8, 155), xytext=(6.5, 130),\n",
        "            fontsize=10, ha='center', color=color_outlier, fontweight='bold',\n",
        "            arrowprops=dict(arrowstyle='->', color=color_outlier, lw=2))\n",
        "ax2.annotate('🚨 OUTLIER\\nPaciente crítico', xy=(9, 180), xytext=(7.5, 145),\n",
        "            fontsize=10, ha='center', color=color_outlier, fontweight='bold',\n",
        "            arrowprops=dict(arrowstyle='->', color=color_outlier, lw=2))\n",
        "ax2.text(0.5, 0.95, f'❌ Media distorsionada (+{media_outliers - mediana_outliers:.1f} lpm)', \n",
        "         transform=ax2.transAxes, fontsize=11, ha='center', \n",
        "         bbox=dict(boxstyle='round', facecolor='lightcoral', alpha=0.7))\n",
        "\n",
        "# --- GRÁFICO 3: Boxplot Comparativo ---\n",
        "ax3 = axes[1, 0]\n",
        "bp = ax3.boxplot([datos_normales, datos_con_outliers], \n",
        "                  labels=['Sin Outliers', 'Con Outliers'],\n",
        "                  patch_artist=True, widths=0.6,\n",
        "                  boxprops=dict(facecolor='lightblue', alpha=0.7, linewidth=2),\n",
        "                  medianprops=dict(color=color_mediana, linewidth=4),\n",
        "                  whiskerprops=dict(linewidth=2),\n",
        "                  capprops=dict(linewidth=2),\n",
        "                  flierprops=dict(marker='o', markersize=12, markerfacecolor=color_outlier, \n",
        "                                 markeredgecolor='black', markeredgewidth=2))\n",
        "ax3.set_title('📊 Boxplot: Visualización de Outliers', fontsize=14, fontweight='bold', pad=15)\n",
        "ax3.set_ylabel('Frecuencia Cardíaca (lpm)', fontsize=12, fontweight='bold')\n",
        "ax3.grid(True, alpha=0.3, linestyle=':', axis='y')\n",
        "ax3.text(1, 155, '← Outliers\\ndetectados', fontsize=10, ha='left', \n",
        "         color=color_outlier, fontweight='bold')\n",
        "ax3.axhline(mediana_normal, color=color_mediana, linewidth=2, linestyle=':', \n",
        "            alpha=0.5, label='Mediana normal')\n",
        "\n",
        "# Añadir anotaciones al boxplot\n",
        "ax3.text(0.5, 0.05, \n",
        "         '💡 La línea verde en la caja representa la MEDIANA\\n(valor central que NO se afecta por outliers)',\n",
        "         transform=ax3.transAxes, fontsize=10, ha='center', \n",
        "         bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.8))\n",
        "\n",
        "# --- GRÁFICO 4: Barra Comparativa del Impacto ---\n",
        "ax4 = axes[1, 1]\n",
        "categorias = ['Sin Outliers', 'Con Outliers']\n",
        "x_pos = np.arange(len(categorias))\n",
        "width = 0.35\n",
        "\n",
        "medias = [media_normal, media_outliers]\n",
        "medianas = [mediana_normal, mediana_outliers]\n",
        "\n",
        "bars1 = ax4.bar(x_pos - width/2, medias, width, label='Media (Promedio)', \n",
        "                color=color_media, alpha=0.8, edgecolor='black', linewidth=2)\n",
        "bars2 = ax4.bar(x_pos + width/2, medianas, width, label='Mediana', \n",
        "                color=color_mediana, alpha=0.8, edgecolor='black', linewidth=2)\n",
        "\n",
        "# Añadir valores en las barras\n",
        "for i, (bar1, bar2) in enumerate(zip(bars1, bars2)):\n",
        "    height1 = bar1.get_height()\n",
        "    height2 = bar2.get_height()\n",
        "    ax4.text(bar1.get_x() + bar1.get_width()/2., height1 + 2,\n",
        "            f'{height1:.1f}', ha='center', va='bottom', fontweight='bold', fontsize=11)\n",
        "    ax4.text(bar2.get_x() + bar2.get_width()/2., height2 + 2,\n",
        "            f'{height2:.1f}', ha='center', va='bottom', fontweight='bold', fontsize=11)\n",
        "\n",
        "ax4.set_title('📈 Comparación: Sensibilidad a Outliers', fontsize=14, fontweight='bold', pad=15)\n",
        "ax4.set_ylabel('Frecuencia Cardíaca (lpm)', fontsize=12, fontweight='bold')\n",
        "ax4.set_xticks(x_pos)\n",
        "ax4.set_xticklabels(categorias, fontsize=11, fontweight='bold')\n",
        "ax4.legend(fontsize=11, loc='upper left')\n",
        "ax4.grid(True, alpha=0.3, linestyle=':', axis='y')\n",
        "ax4.set_ylim(0, 120)\n",
        "\n",
        "# Añadir anotación de diferencia\n",
        "diferencia = media_outliers - mediana_outliers\n",
        "ax4.annotate('', xy=(1 - width/2, media_outliers), xytext=(1 + width/2, mediana_outliers),\n",
        "            arrowprops=dict(arrowstyle='<->', color='red', lw=3))\n",
        "ax4.text(1, (media_outliers + mediana_outliers)/2, \n",
        "         f'  Distorsión:\\n  {diferencia:.1f} lpm', \n",
        "         fontsize=11, fontweight='bold', color='red', ha='left', va='center',\n",
        "         bbox=dict(boxstyle='round', facecolor='white', edgecolor='red', alpha=0.9))\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "# ============================================================================\n",
        "# CONCLUSIÓN Y APLICACIÓN AL PROYECTO\n",
        "# ============================================================================\n",
        "\n",
        "print(\"\\n\" + \"=\"*70)\n",
        "print(\"🎓 CONCLUSIÓN: ¿Por qué usamos MEDIANA en el script?\")\n",
        "print(\"=\"*70)\n",
        "print(\"\")\n",
        "print(\"✅ VENTAJAS de la MEDIANA:\")\n",
        "print(\"   1. 🛡️  ROBUSTA ante valores extremos (pacientes críticos, errores de medición)\")\n",
        "print(\"   2. 📊  Representa el valor CENTRAL real de la mayoría de pacientes\")\n",
        "print(\"   3. 🎯  No se distorsiona por outliers (media sí se distorsiona)\")\n",
        "print(\"   4. 🏥  Ideal para datos médicos donde outliers son informativos pero atípicos\")\n",
        "print(\"\")\n",
        "print(\"❌ DESVENTAJAS de la MEDIA con outliers:\")\n",
        "print(\"   1. ⚠️  Se DISTORSIONA fácilmente por valores extremos\")\n",
        "print(f\"   2. 📉  En nuestro ejemplo: {media_outliers - mediana_outliers:.1f} lpm de error\")\n",
        "print(\"   3. 🚫  NO representa la distribución típica de pacientes\")\n",
        "print(\"   4. 💊  Puede llevar a imputaciones incorrectas en ML\")\n",
        "print(\"\")\n",
        "print(\"🔬 APLICACIÓN EN NUESTRO DATASET:\")\n",
        "print(\"   • Dataset: 91,713 pacientes en UCI\")\n",
        "print(\"   • Variables numéricas: frecuencia cardíaca, presión arterial, temperatura, etc.\")\n",
        "print(\"   • Outliers esperados: pacientes en estado crítico, valores atípicos\")\n",
        "print(\"   • Decisión: MEDIANA para preservar la distribución típica\")\n",
        "print(\"=\"*70)\n",
        "\n",
        "print(\"\\n🔬 ¿Por qué NO eliminar filas con missing values?\")\n",
        "print(\"   • Preserva el tamaño muestral (91,713 pacientes)\")\n",
        "print(\"   • Evita sesgo de selección\")\n",
        "print(\"   • Cada paciente aporta información valiosa\")\n",
        "print(\"   • Missing puede ser informativo (menos monitoreo = menos crítico)\")\n"
    ]
}

# Nueva celda markdown explicativa
nueva_celda_markdown = {
    "cell_type": "markdown",
    "id": "outliers_explanation",
    "metadata": {},
    "source": [
        "### 🎯 ¿Qué son los OUTLIERS?\n",
        "\n",
        "Los **outliers** (valores atípicos) son observaciones que se desvían significativamente del resto de los datos:\n",
        "\n",
        "| Concepto | Definición | Ejemplo Médico |\n",
        "|----------|------------|----------------|\n",
        "| **Valor Normal** | Dentro del rango esperado | Frecuencia cardíaca: 60-100 lpm |\n",
        "| **Outlier** | Valor extremo o inusual | Frecuencia cardíaca: 180 lpm (paciente crítico) |\n",
        "\n",
        "---\n",
        "\n",
        "### 📊 Interpretación de las Visualizaciones Anteriores\n",
        "\n",
        "**Gráfico 1 (Datos Normales):**\n",
        "- Todos los puntos azules están en el rango 68-80 lpm\n",
        "- Media ≈ Mediana: ambos representan bien los datos\n",
        "- ✅ Cualquier medida de tendencia central funciona\n",
        "\n",
        "**Gráfico 2 (Con Outliers):**\n",
        "- 2 puntos rojos (155 y 180 lpm) son outliers\n",
        "- La media se **infla** hacia los outliers\n",
        "- La mediana se mantiene **estable** en el valor central\n",
        "- ✅ La mediana representa mejor a la mayoría de pacientes\n",
        "\n",
        "**Boxplot (Gráfico 3):**\n",
        "- La **línea verde** dentro de la caja es la mediana\n",
        "- Los **puntos rojos** fuera de los bigotes son outliers detectados\n",
        "- La caja contiene el 50% central de los datos\n",
        "\n",
        "**Gráfico de Barras (Gráfico 4):**\n",
        "- Muestra numéricamente la **distorsión** causada por outliers\n",
        "- La flecha roja indica cuánto se aleja la media de la mediana\n",
        "- Mayor diferencia = mayor impacto de outliers\n",
        "\n",
        "---\n",
        "\n",
        "### 💡 Analogía Simple\n",
        "\n",
        "Imagina que quieres conocer el **ingreso típico** en una empresa:\n",
        "\n",
        "- 9 empleados ganan: $30,000, $32,000, $31,000, $33,000, $30,500, $31,500, $32,500, $31,000, $30,000\n",
        "- 1 CEO gana: $500,000\n",
        "\n",
        "**Media:** $81,150 ❌ (no representa a nadie)\n",
        "**Mediana:** $31,250 ✅ (representa al empleado típico)\n",
        "\n",
        "**En medicina es igual:** la mediana representa mejor al paciente típico cuando hay casos críticos (outliers)."
    ]
}

# Reemplazar la celda original con las nuevas celdas
notebook['cells'][target_cell_index] = nueva_celda_codigo

# Insertar la celda markdown después de la celda de código
notebook['cells'].insert(target_cell_index + 1, nueva_celda_markdown)

# Guardar el notebook modificado
with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"\nNotebook modificado exitosamente!")
print(f"Celda original reemplazada con visualizacion mejorada")
print(f"Celda markdown explicativa agregada")
print(f"Ubicacion: {notebook_path}")
